// src/renderer/Components/SettingsWindow/GeneralSettings.tsx
import { Stack, StackItem, Toggle } from "@fluentui/react";
import { FC, useState } from "react";
import { getSettings, saveSettings } from "../../Actions";

export const GeneralSettings: FC = () => {
    const settings = getSettings();
    const [hideWindowOnBlur, setHideWindowOnBlur] = useState<boolean>(settings.generalSettings.hideWindowOnBlur);

    const toggleHideWindowOnBlur = async () => {
        settings.generalSettings.hideWindowOnBlur = !hideWindowOnBlur;
        setHideWindowOnBlur(settings.generalSettings.hideWindowOnBlur);
        await saveSettings(settings);
    };

    return (
        <Stack tokens={{ childrenGap: 20, padding: 20 }}>
            <StackItem>
                <Toggle
                    label="Hide window on blur"
                    checked={hideWindowOnBlur}
                    onChange={() => toggleHideWindowOnBlur()}
                />
            </StackItem>
        </Stack>
    );
};

// src/renderer/Components/SettingsWindow/GeneralSettings.vue
<template>
    <USettingList title="General settings">
        <template v-slot:settings>
            <USetting>
                <template v-slot:label>Hide window on blur</template>
                <template v-slot:body>
                    <UToggle :toggled="settings.generalSettings.hideWindowOnBlur" @toggle="updateHideWindowOnBlur" />
                </template>
            </USetting>
        </template>
    </USettingList>
</template>

<script lang="ts" setup>
import { USettingList, USetting, UToggle } from "ueli-designsystem";
import { Settings } from "../../../common/Settings";
import { IpcChannel } from "../../../common/IpcChannel";
import { ref } from "vue";
import { saveSettings } from "./Actions";
import { ObjectUtility } from "../../../common/ObjectUtility";

const settings = ref<Settings>(window.Bridge.ipcRenderer.sendSync<unknown, Settings>(IpcChannel.GetSettings));

const save = async (): Promise<void> => saveSettings(ObjectUtility.clone<Settings>(settings.value));

const updateHideWindowOnBlur = (value: boolean) => {
    settings.value.generalSettings.hideWindowOnBlur = value;
    save();
};
</script>
